import { Inter } from "next/font/google";
import "../styles/index.scss";
import Header from "@/components/header/Header";
import { MyState } from "@/context/ContextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        {/* <div > */}
        <MyState>
          <Header />
          {children}
        </MyState>
        {/* </div> */}
      </body>
    </html>
  );
}
